version: "2.2"
services:
  auth:
    build:
      context: ../auth_jwt_fastapi
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - auth_network
    env_file:
      - .env


  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
    - "6379:6379"
    networks:
      - auth_network
    volumes:
     - redis_data:/data
    command: redis-server --bind 0.0.0.0 --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env

  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - auth_network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
 redis_data:
 postgres_data:

networks:
  auth_network:
    driver: bridge

